"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///CWE-022-codeql_1.py:1:26:1:32""]].","/CWE-022-codeql_1.py","23","23","23","30"
"Code injection","Interpreting unsanitized user input as code allows a malicious user to perform arbitrary code execution.","error","This code execution depends on a [[""user-provided value""|""relative:///CWE-094-author_1.py:1:26:1:32""]].","/CWE-094-author_1.py","40","14","40","17"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///CWE-094-author_1.py:42:25:42:25""]] flows to this location and may be exposed to an external user.","/CWE-094-author_1.py","20","12","20","34"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-020-codeql_3.py","28","5","28","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-022-codeql_1.py","35","5","35","23"
"Use of insecure SSL/TLS version","Using an insecure SSL/TLS version may leave the connection vulnerable to attacks.","warning","Insecure SSL/TLS protocol version TLSv1 allowed by [[""call to ssl.SSLContext""|""relative:///CWE-327-codeql_2.py:8:15:8:53""]].
Insecure SSL/TLS protocol version TLSv1_1 allowed by [[""call to ssl.SSLContext""|""relative:///CWE-327-codeql_2.py:8:15:8:53""]].","/CWE-327-codeql_2.py","17","16","17","22"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///CWE-020-codeql_3.py:1:36:1:42""]].","/CWE-020-codeql_3.py","21","25","21","30"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///CWE-020-codeql_4.py:1:36:1:42""]].","/CWE-020-codeql_4.py","10","25","10","34"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///CWE-601-codeql_1.py:1:26:1:32""]].","/CWE-601-codeql_1.py","16","29","16","36"
