"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///CWE-022-author_1.py:2:26:2:32""]].","/CWE-022-author_1.py","35","23","35","32"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///CWE-022-author_1.py:2:26:2:32""]].","/CWE-022-author_1.py","36","19","36","28"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///CWE-022-codeql_1.py:2:26:2:32""]].","/CWE-022-codeql_1.py","19","27","19","35"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///CWE-116-author_1.py:2:29:2:35""]].","/CWE-116-author_1.py","26","26","26","34"
"Uncontrolled data used in path expression","Accessing paths influenced by users can allow an attacker to access unexpected resources.","error","This path depends on a [[""user-provided value""|""relative:///CWE-116-author_1.py:2:29:2:35""]].","/CWE-116-author_1.py","31","28","31","36"
"Arbitrary file write during tarfile extraction","Extracting files from a malicious tar archive without validating that the destination file path is within the destination directory can cause files outside the destination directory to be overwritten.","error","This file extraction depends on a [[""potentially untrusted source""|""relative:///CWE-022-codeql_2.py:19:10:19:37""]].","/CWE-022-codeql_2.py","26","29","26","33"
"Uncontrolled command line","Using externally controlled strings in a command line may allow a malicious user to change the meaning of the command.","error","This command line depends on a [[""user-provided value""|""relative:///CWE-078-codeql_1.py:2:26:2:32""]].","/CWE-078-codeql_1.py","23","33","23","47"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///CWE-020-codeql_2.py:4:26:4:32""]].","/CWE-020-codeql_2.py","29","12","29","35"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///CWE-094-sonar_1.py:1:26:1:32""]].","/CWE-094-sonar_1.py","25","28","25","104"
"Reflected server-side cross-site scripting","Writing user input directly to a web page allows for a cross-site scripting vulnerability.","error","Cross-site scripting vulnerability due to a [[""user-provided value""|""relative:///CWE-730-codeql_2.py:1:26:1:32""]].","/CWE-730-codeql_2.py","27","12","27","23"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///CWE-022-codeql_1.py:24:33:24:33""]] flows to this location and may be exposed to an external user.","/CWE-022-codeql_1.py","25","24","25","54"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///CWE-116-author_1.py:32:25:32:25""]] flows to this location and may be exposed to an external user.","/CWE-116-author_1.py","33","25","33","55"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///CWE-918-codeql_1.py:29:52:29:52""]] flows to this location and may be exposed to an external user.","/CWE-918-codeql_1.py","30","16","30","26"
"Information exposure through an exception","Leaking information about an exception, such as messages and stack traces, to an external user can expose implementation details that are useful to an attacker for developing a subsequent exploit.","error","[[""Stack trace information""|""relative:///CWE-918-codeql_2.py:29:41:29:41""]] flows to this location and may be exposed to an external user.","/CWE-918-codeql_2.py","30","16","30","26"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-020-codeql_2.py","32","5","32","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-022-author_1.py","42","5","42","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-022-codeql_1.py","42","5","42","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-079-codeql_1.py","24","5","24","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-090-codeql_2.py","33","5","33","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-116-author_1.py","39","5","39","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-611-author_1.py","31","5","31","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-643-sonar_1.py","25","5","25","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-730-codeql_1.py","25","5","25","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-730-codeql_2.py","30","5","30","23"
"Flask app is run in debug mode","Running a Flask app in debug mode may allow an attacker to run arbitrary code through the Werkzeug debugger.","error","A Flask app appears to be run in debug mode. This may allow an attacker to run arbitrary code through the debugger.","/CWE-918-codeql_2.py","49","1","49","19"
"URL redirection from remote source","URL redirection based on unvalidated user input may cause redirection to malicious web sites.","error","Untrusted URL redirection depends on a [[""user-provided value""|""relative:///CWE-020-codeql_3.py:1:36:1:42""]].","/CWE-020-codeql_3.py","18","29","18","34"
"Full server-side request forgery","Making a network request to a URL that is fully user-controlled allows for request forgery attacks.","error","The full URL of this request depends on a [[""user-provided value""|""relative:///CWE-918-codeql_1.py:2:26:2:32""]].","/CWE-918-codeql_1.py","28","20","28","61"
